### ISSUE TITLE
globalObject() return null

### ISSUE THREAD

**Issue by lolobug** [mceSystems/node-jsc#21]
![image](https://user-images.githubusercontent.com/3275789/47840073-088abe00-ddf0-11e8-832a-3fc3a9c175d9.png)

See as above.
very simple use:
![image](https://user-images.githubusercontent.com/3275789/47840437-3b818180-ddf1-11e8-804a-4a668fd4be56.png)

**Comment by lolobug** [comment]
solved by recompile

**Comment by MCE-KobyBo** [comment]
Great. Happy to see that you're trying node-jsc :)
